# Generated by Django 4.2.5 on 2023-12-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appheri', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
